
petBoss: petBoss.cpp expressionBoss.h expressionBoss.cpp expression.h expression.cpp stringmath.h stringmath.cpp stringmath.cpp stringmath.tpp
	g++ petBoss.cpp expression.cpp  stringmath.cpp expressionBoss.cpp -o petBoss -std=c++11 -lgmpxx -lgmp -O3
